apiVersion: v1
kind: Service
metadata:
  name: my-world
  namespace: default
spec:
  selector:
    app: my-world
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 80
